### ISSUE TITLE
todo chicken bucket list

### ISSUE THREAD

**Issue by aldo-sanchez** [michaelrogers/socket-game-platform#19]
## Must be done
- [x] Stability 
- [x] creating a new game should allow me to start playing - Michael
- [x] scoreboard - Aldo
- [x] start game (simple)
- [x] Create presentation
- [x] some styling - Alejandro
- [x] determine winner or loser - Aldo (sets this.state.winner with player that won, once we start styling will display on DOM, currently just console logging)
- [x] restart canvas or make the lobby a button a hard refresh. maybe we can kill the canvas. and restart look at p5 docs - Jorge

## High Reward Easy Enough
- [x] Add sounds
- [ ] user feed
- [ ] Live db update of games (lobby)
- [ ] Different images for sprites
- [ ] different animations (polish)
- [ ] start game (polish)

## Nice to have
- [ ] timed game

# Will Be Done
- [x] DRINK BEER
